### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by bhaumik1991** [mrdishant/Paytm-All-in-one-flutter-sdk#11]
Getting an error {errorMessage: networkError, error: true} like this in Production,
Any solution to solve this??

**Comment by mrdishant** [comment]
Can you check all params with Paytm Dashboard?

I mean MID, Merchant Key, Website etc..

**Comment by riskyRahul** [comment]
Hello. Friends, I have a problem with this library, please help me. I have this kind of exception

- My Flutter version is :- {Flutter (Channel master, 1.22.0-10.0.pre.39, on Microsoft Windows [Version 10.0.18363.1139], locale en-GB)}
- Flutter Paytm librery version is:- {paytm: ^1.0.7}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

D/AssistLogs(14200): com.paytm.pgsdk.PaytmPGActivity$SmsConsentBroadCastReciever@b10e141:Receiver started:
D/AndroidRuntime(14200): Shutting down VM
E/AndroidRuntime(14200): FATAL EXCEPTION: main
E/AndroidRuntime(14200): Process: com.example.pro_advisor, PID: 14200
E/AndroidRuntime(14200): java.lang.RuntimeException: Unable to start receiver com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(14200):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4111)
E/AndroidRuntime(14200):        at android.app.ActivityThread.access$1700(ActivityThread.java:242)
E/AndroidRuntime(14200):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2078)
E/AndroidRuntime(14200):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14200):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(14200):        at android.app.ActivityThread.main(ActivityThread.java:7830)
E/AndroidRuntime(14200):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14200):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14200):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/AndroidRuntime(14200): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
Lost connection to device.

**Comment by lakshyapunhani** [comment]
Facing same issue. Any luck with this?

**Comment by AvinashKanjiya** [comment]
same issue  {errorMessage: networkError, error: true} 

please help

**Comment by mrdishant** [comment]
Try Production Key and MID when Paytm App Installed
